title: Doc Projet
description: Documentation du projet
favicon_ico: "/images/image.ico"


# NE RIEN MODIFIER CI-DESSOUS SI VOUS N'ETES PAS CERTAINS DE CE QUE VOUS FAITES

# Th√®me
# remote_theme: Makerspace-Amiens/CraftTheDocs-V1.0
theme: bulma-clean-theme
url: https://github.com/Makerspace-Amiens

